wandb_version: 1

task:
  desc: null
  value: node
dataset:
  desc: null
  value:
  - Amazon_Photo
  - Amazon_Computer
  - Amazon_Fraud
subgraphs:
  desc: null
  value: 256
temperature:
  desc: null
  value: 0.1
augment:
  desc: null
  value:
  - Subgraph
  - Drop
aug_radio:
  desc: null
  value:
  - 0.8
  - 0.2
gnn_layer:
  desc: null
  value: 2
mlp_layer:
  desc: null
  value: 2
input_dim:
  desc: null
  value: 128
hidden_dim:
  desc: null
  value: 256
output_dim:
  desc: null
  value: 32
node_num:
  desc: null
  value: 16
node_group:
  desc: null
  value: 256
node_dim:
  desc: null
  value: 128
threshold:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.01
decay:
  desc: null
  value: 0.0001
max_epoches:
  desc: null
  value: 200
loss_bias:
  desc: null
  value: 10.0
gpu:
  desc: null
  value: -1
seed:
  desc: null
  value: 42
patience:
  desc: null
  value: 10
id:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.1
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709522814.616763
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 76
      - 77
      3:
      - 16
      - 23
      4: 3.11.1
      5: 0.16.3
      6: 4.37.0
      8:
      - 3
      - 5
      13: windows-amd64
